Avoid MegaLinter false positive with .secretlintignore
k8s-at-home/flux-cluster-template pull request #421
Opened 2022-07-31 01:27 UTC by nvuillam

2022-07-31 13:58 UTC, onedr0p commented
https://github.com/oxsecurity/megalinter/issues/816#issuecomment-939210391

Seems like this can point to the .gitignore instead?

2022-08-07 21:14 UTC, nvuillam commented
@onedr0p with MegaLinter v6.3.0, I added the [capability to refer to a .secretlintignore file](https://oxsecurity.github.io/megalinter/latest/descriptors/repository_secretlint/) in .github/linters, please can you allow the job to run to verify that is now ok ?

It will avoid you the MegaLinter failing jobs because of the example key in README file :)

2022-08-07 22:30 UTC, onedr0p commented
I ran it, does that seem expected?

2022-08-07 22:43 UTC, nvuillam commented
Nope, it find the .secretlintignore and uses it but does not take in account the README.md in it :/
Maybe secretlint is not happy with folder stuff... i try something else

2022-08-07 22:54 UTC, onedr0p commented
Maybe test this out on a repo you own so we don't have to go back and forth with running the CI 😄

2022-08-07 23:05 UTC, nvuillam commented
> Maybe test this out on a repo you own so we don't have to go back and forth with running the CI 😄

Indeed :)

Meanwhile if you're tired to the false positive, you can define variable `REPOSITORY_SECRETLINT_DISABLE_ERRORS: true` :)

2022-08-16 07:49 UTC, fabricesemti80 commented
I think this still did not work...

```
❌ Linted [REPOSITORY] files with [secretlint]: Found 1 error(s) - (1.2s) (expand for details)
  - Using [secretlint v5.2.3] https://oxsecurity.github.io/megalinter/latest/v6.4.0/descriptors/repository_secretlint
  - MegaLinter key: [REPOSITORY_SECRETLINT]
  - Rules config: [.secretlintrc.json]
  - Ignore file: [/github/workspace/.github/linters/.secretlintignore]
  --Error detail:
  
  /github/workspace/README.md
    483:14  error  [PrivateKey] found private key: -----BEGIN OPENSSH PRIVATE KEY-----
                    ...
                -----END OPENSSH PRIVATE KEY-----  @secretlint/secretlint-rule-preset-recommend > @secretlint/secretlint-rule-privatekey
  
  ✖ 1 problem (1 error, 0 warnings)
  ```
 At least I still see this in the output...?

2022-08-16 11:58 UTC, nvuillam commented
@fabricesemti80 it's an issue with secretlint >_<
It will find another way

2022-08-16 12:48 UTC, onedr0p commented
For that file, just remove it from your own repos README.md

2022-08-16 12:58 UTC, onedr0p commented
Ideally we should use `secretlintignore` and ignore the README

2022-08-16 20:57 UTC, nvuillam commented
I'm sure it will work like that but I didn't want to bother your root folder with a .secretlintignore :/
If it is ok for you I can do that and the PR will pass :)

2022-08-16 20:59 UTC, onedr0p commented
That should be be fine.

2022-08-16 21:15 UTC, onedr0p commented on README.md
> +      <!-- secretlint-disable -->
```suggestion
```

2022-08-16 21:15 UTC, onedr0p commented on README.md
> +      <!-- secretlint-enable -->
```suggestion
```

2022-08-16 21:15 UTC, onedr0p requested changes
No need for this in the readme

2022-08-16 21:27 UTC, onedr0p commented on .secretlintignore
> +README.md
```suggestion
README.md

```

2022-08-16 21:27 UTC, onedr0p approved these changes

2022-08-16 21:28 UTC, merged